version: '3.8'

services:
  app:
    build:
      context: .
    container_name: assessment-hubspot
    ports:
      - "8000:8000"
    depends_on:
      - redis
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - HUBSPOT_CLIENT_SECRET=X
      - HUBSPOT_CLIENT_ID=X
    volumes:
      - ./backend:/app

  redis:
    image: redis:latest
    container_name: redis
    ports:
      - "6379:6379"
